### PR TITLE
Merging.

### PR DESCRIPTION
**Pull request by MerlinisaG**
Merging branches.

### CODE REVIEW

**Comment by alberttheprince** [comment]
What is the point of this PR?

**Comment by alberttheprince** [comment]
Is this adding emotes from https://github.com/Mustachedom/md-drugs as well? Please keep to the format of rpemotes-reborn, just to make it easier to actually review these changes.

Additionally, I'm not sure why those use PansexualPropBone and not just PropBone.

**Comment by alberttheprince** [comment]
Below Mustachedom emotes if you want to resubmit, in the rpemotes format:

```   
["uncuff"] = { -- Emotes by Mustachedom
        "mp_arresting",
        "a_uncuff",
        "Uncuff", 
        AnimationOptions = {
            EmoteLoop = true,
            EmoteMoving = true
        }
    },
    ["edible"] = { -- Emotes by Mustachedom
        "mp_player_inteat@burger",
        "mp_player_int_eat_burger",
        "edible",
        AnimationOptions = {   
            EmoteLoop = false,
            EmoteMoving = true
        }
    },
    ["shootup"] = { -- Emotes by Mustachedom
        "rcmpaparazzo1ig_4",
        "miranda_shooting_up",
        "Shoot Up",
        AnimationOptions = {
            EmoteLoop = true,
            EmoteMoving = true,
            Prop = 'prop_syringe_01',
            PropBone = 18905,
            PropPlacement = {
                0.11,
                0.03,
                0.0,
                -124.0,
                0.0,
                0.0
            },
        }
    },

**Comment by MerlinisaG** [comment]
If you see in my main branch, I corrected this. Also... same issue persists with the latest release brother.

**Pull request closed without merging**
